### ISSUE TITLE
new package: inotify

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-packages#1]
Please create a package for inotify

**Comment by tylerflint** [comment]
http://www.phoenixframework.org/docs/installation#section-inotify-tools-for-linux-users-

**Comment by philipgiuliani** [comment]
Isn't inotify already in the repo? I am using
```yaml
run.config:
  engine: elixir

  dev_packages:
    - inotify-tools-3.14
```

and it works fine!
